name: Prune Stale Openshift CI Resources on GCP
run-name: Openshift CI Pruner
on:
  workflow_dispatch:
jobs:
  prune:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.OCI_SVC_ACCT_GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'List Old CI Jobs'
      run: |
        # project id is embedded in the service account credentials
        ./gcp/oci-pruner.sh -j

    - name: 'Prune 2 CI Jobs'
      run: |
        ./gcp/oci-pruner.sh -j | head -n2 | xargs -r ./gcp/oci-pruner.sh
